'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FYD_3F.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AmozaonPay_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AmozaonPay_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appt_icon_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appt_icon_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appt_icon_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appt_icon_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appt_icon_white2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appt_icon_white2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_appt_img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_appt_img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_dr_img_m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_dr_img_m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_dr_img2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_dr_img2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_dr_img3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_dr_img3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_DR_reg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_DR_reg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_drRec_img11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_drRec_img11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_drRec_img9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_drRec_img9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_payment_img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_payment_img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_pt_img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_pt_img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_pt_img10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_pt_img10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_pt_img3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_pt_img3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_pt_img9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_pt_img9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_ptRec_img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_ptRec_img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_report_img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_report_img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bck_reportREC_img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck_reportREC_img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BharatPe_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BharatPe_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cpyryt_symbl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cpyryt_symbl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cpyryt_symbol2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cpyryt_symbol2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dr_icon_color_512px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dr_icon_color_512px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dr_icon_white_512px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dr_icon_white_512px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fyd_main_logo_black_transparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fyd_main_logo_black_transparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fyd_main_logo_transparent_cropped() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fyd_main_logo_transparent_cropped", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpay_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpay_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home_512px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_512px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home_white_512px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_white_512px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property patient_icon_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("patient_icon_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property payment_icon_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payment_icon_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property payment_icon_color2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payment_icon_color2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property payment_icon_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payment_icon_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paytm_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paytm_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Phonepe_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Phonepe_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pt_icon_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pt_icon_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pwd1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pwd1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property report_icon_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report_icon_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property report_icon_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report_icon_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property searcg_icon2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("searcg_icon2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upi_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upi_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upi_scanner_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upi_scanner_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property username_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("username_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhatsappPay_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhatsappPay_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
